---
- hosts: web
  gather_facts: yes
  tasks:
  - name: start
    become_user: vagrant
    shell: export DB_HOST=mongodb://192.168.33.11:27017/posts; cd app; node seeds/seed.js; npm install; screen -d -m npm start 
