---
- hosts: db
  gather_facts: yes
  become: true
# install mongodb in db instance and ensure it's running
  tasks:
  - name: installing mongo pre-requisites
    shell: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv D68FA50FEA312927; echo "deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list; sudo apt update -y
  - name: installing mongo pre-requisites
    apt:
      pkg:
        - mongodb-org=3.2.20
        - mongodb-org-server=3.2.20
        - mongodb-org-shell=3.2.20
        - mongodb-org-mongos=3.2.20
        - mongodb-org-tools=3.2.20
      update_cache: yes
  - name: allow 0.0.0.0
    ansible.builtin.lineinfile:
      path: /etc/mongod.conf
      regexp: '^bind_ip = '
      insertafter: '^#bind_ip = '
      line: bind_ip = 0.0.0.0
  - name: restart and enable mongod
    service: name=mongod state=restarted enabled=yes  

