---
- hosts: web
  gather_facts: yes
  become: true
  tasks:
  - name: Copy nginx reverse proxy configs
    copy:
      src: /home/ubuntu/Ansible/sync/default
      dest: /etc/nginx/sites-available/
      force: yes  
